import asyncio
import base64
import logging
import os
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

import boto3
import uvicorn
from dotenv import load_dotenv
from fastapi import FastAPI
from faster_whisper import WhisperModel
from pydantic import BaseModel

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger("python-service")


@dataclass
class Settings:
    host: str = os.getenv("PYTHON_HOST", "127.0.0.1")
    port: int = int(os.getenv("PYTHON_PORT", "8000"))
    whisper_model: str = os.getenv("FASTER_WHISPER_MODEL", "base.en")
    whisper_device: str = os.getenv("FASTER_WHISPER_DEVICE", "cpu")
    whisper_compute_type: str = os.getenv("FASTER_WHISPER_COMPUTE_TYPE", "int8")
    aws_region: str = os.getenv(
        "AWS_REGION",
        os.getenv("AWS_DEFAULT_REGION", "us-east-1"),
    )
    polly_voice_id: str = os.getenv("POLLY_VOICE_ID", "Brian")
    polly_engine: str = os.getenv("POLLY_ENGINE", "neural")


settings = Settings()
app = FastAPI(title="Discord Voice Prototype Service")


class AudioProcessRequest(BaseModel):
    guild_id: int
    speaker_id: Optional[int] = None
    utterance_id: int
    sample_rate: int
    channels: int
    audio_base64: str


class AudioProcessResponse(BaseModel):
    transcript: str
    reply_text: Optional[str] = None
    tts_audio_base64: Optional[str] = None
    tts_audio_format: Optional[str] = None


class HealthResponse(BaseModel):
    status: str
    whisper_model: str


class VoiceService:
    def __init__(self, config: Settings) -> None:
        self.config = config
        logger.info(
            "loading faster-whisper model=%s device=%s compute_type=%s",
            config.whisper_model,
            config.whisper_device,
            config.whisper_compute_type,
        )
        self.model = WhisperModel(
            config.whisper_model,
            device=config.whisper_device,
            compute_type=config.whisper_compute_type,
        )
        logger.info("faster-whisper model loaded")
        self.polly = boto3.client("polly", region_name=config.aws_region)
        logger.info(
            "configured aws polly region=%s voice=%s engine=%s",
            config.aws_region,
            config.polly_voice_id,
            config.polly_engine,
        )

    def transcribe_wav(self, wav_path: Path) -> str:
        segments, info = self.model.transcribe(
            str(wav_path),
            vad_filter=True,
            language="en",
        )
        transcript = " ".join(segment.text.strip() for segment in segments).strip()
        logger.info(
            "transcript generated language=%s duration=%.2fs text=%r",
            getattr(info, "language", "unknown"),
            getattr(info, "duration", 0.0),
            transcript,
        )
        return transcript

    def synthesize_tts_sync(self, text: str) -> bytes:
        response = self.polly.synthesize_speech(
            Engine=self.config.polly_engine,
            OutputFormat="mp3",
            SampleRate="24000",
            Text=text,
            TextType="text",
            VoiceId=self.config.polly_voice_id,
        )
        audio_stream = response["AudioStream"]
        try:
            audio_bytes = audio_stream.read()
            logger.info("tts generated bytes=%s", len(audio_bytes))
            return audio_bytes
        finally:
            audio_stream.close()

    async def synthesize_tts(self, text: str) -> bytes:
        return await asyncio.to_thread(self.synthesize_tts_sync, text)


voice_service = VoiceService(settings)


@app.get("/health", response_model=HealthResponse)
async def health() -> HealthResponse:
    logger.info("health check")
    return HealthResponse(status="ok", whisper_model=settings.whisper_model)


@app.post("/process-audio", response_model=AudioProcessResponse)
async def process_audio(request: AudioProcessRequest) -> AudioProcessResponse:
    audio_bytes = base64.b64decode(request.audio_base64)
    logger.info(
        "received audio chunk guild_id=%s utterance_id=%s speaker_id=%s bytes=%s sample_rate=%s channels=%s",
        request.guild_id,
        request.utterance_id,
        request.speaker_id,
        len(audio_bytes),
        request.sample_rate,
        request.channels,
    )

    with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as temp_file:
        wav_path = Path(temp_file.name)
        temp_file.write(audio_bytes)

    try:
        transcript = await asyncio.to_thread(voice_service.transcribe_wav, wav_path)
    finally:
        wav_path.unlink(missing_ok=True)

    if not transcript:
        logger.info("empty transcript for utterance_id=%s", request.utterance_id)
        return AudioProcessResponse(transcript="", reply_text=None)

    reply_text = choose_reply(transcript)
    logger.info(
        "selected response utterance_id=%s transcript=%r reply=%r",
        request.utterance_id,
        transcript,
        reply_text,
    )

    tts_audio = await voice_service.synthesize_tts(reply_text)
    return AudioProcessResponse(
        transcript=transcript,
        reply_text=reply_text,
        tts_audio_base64=base64.b64encode(tts_audio).decode("utf-8"),
        tts_audio_format="mp3",
    )


def choose_reply(transcript: str) -> str:
    normalized = transcript.lower().strip()

    if "hello bot" in normalized:
        return "Hello! Voice pipeline is working."
    if "what time is it" in normalized:
        current_time = datetime.now().strftime("%I:%M %p").lstrip("0")
        return f"It is {current_time}."
    if normalized.startswith("say "):
        requested = transcript[4:].strip()
        return f"Test successful. You asked me to say: {requested}"
    if "test successful" in normalized:
        return "Voice test successful."

    return f"I heard you say: {transcript}"


if __name__ == "__main__":
    uvicorn.run(app, host=settings.host, port=settings.port)
